In [1]:
import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport

In [2]:
df = pd.read_csv(r'C:\Users\moa57\surveyFA2.csv')

In [3]:
print(df.shape)

(1259, 25)


In [4]:
df.head()

Age  Gender         Country state self_employed family_history treatment  \
0   37  Female   United States    IL           NaN             No       Yes   
1   44       M   United States    IN           NaN             No        No   
2   32    Male          Canada   NaN           NaN             No        No   
3   31    Male  United Kingdom   NaN           NaN            Yes       Yes   
4   31    Male   United States    TX           NaN             No        No   

  work_interfere    no_employees remote_work  ...   anonymity  \
0          Often           45809          No  ...         Yes   
1         Rarely  More than 1000          No  ...  Don't know   
2         Rarely           45809          No  ...  Don't know   
3          Often          26-100          No  ...          No   
4          Never         100-500         Yes  ...  Don't know   

                leave mental_health_consequence phys_health_consequence  \
0       Somewhat easy                        No                      No   
1          Don't know                     Maybe                      No   
2  Somewhat difficult                        No                      No   
3  Somewhat difficult                       Yes                     Yes   
4          Don't know                        No                      No   

      coworkers supervisor mental_health_interview phys_health_interview  \
0  Some of them        Yes                      No                 Maybe   
1            No         No                      No                    No   
2           Yes        Yes                     Yes                   Yes   
3  Some of them         No                   Maybe                 Maybe   
4  Some of them        Yes                     Yes                   Yes   

  mental_vs_physical obs_consequence  
0                Yes              No  
1         Don't know              No  
2                 No              No  
3                 No             Yes  
4         Don't know              No  

[5 rows x 25 columns]

In [5]:
df.columns

Index(['Age', 'Gender', 'Country', 'state', 'self_employed', 'family_history',
       'treatment', 'work_interfere', 'no_employees', 'remote_work',
       'tech_company', 'benefits', 'care_options', 'wellness_program',
       'seek_help', 'anonymity', 'leave', 'mental_health_consequence',
       'phys_health_consequence', 'coworkers', 'supervisor',
       'mental_health_interview', 'phys_health_interview',
       'mental_vs_physical', 'obs_consequence'],
      dtype='object')

In [6]:
df2 = df[["Country", "self_employed", "family_history", "treatment"]]

In [7]:
df["Gender"].value_counts()

Male                                              615
male                                              206
Female                                            121
M                                                 116
female                                             62
F                                                  38
m                                                  34
f                                                  15
Make                                                4
Woman                                               3
Male                                                3
Female                                              2
Man                                                 2
Cis Male                                            2
Female (trans)                                      2
Agender                                             1
Nah                                                 1
All                                                 1
Trans-female                

In [8]:
df["Age"].describe()

count    1.259000e+03
mean     7.942815e+07
std      2.818299e+09
min     -1.726000e+03
25%      2.700000e+01
50%      3.100000e+01
75%      3.600000e+01
max      1.000000e+11
Name: Age, dtype: float64

In [9]:
df3=df.copy()
df3['Gender_0']=df3['Gender']
df3['Gender_0'].replace({'male': 'Male', 
                         'female': 'Female', 
                         'f': 'Female', 
                         'm': 'Male', 
                         'F': 'Female', 
                         'M': 'Male',
                         'Make': 'Male', 
                         'Woman': 'Female', 
                         'woman': 'Female', 
                         'Female (cis)': 'Female',
                        'Male ': 'Male',
                        'Man': 'Male',
                        'Mail': 'Male',
                        'maile': 'Male',
                        'Male CIS': 'Male',
                        'femail': 'Female',
                        'Femake': 'Female',
                        'Cis Female': 'Female',
                        'Cis Man': 'Male',
                        'Cis Male': 'Male',
                        'Female ': 'Female',
                        'Male (CIS)': 'Male',
                        'cis male': 'Male',
                        'Malr': 'Male',
                        'Mal': 'Male',
                        'cis-female/femme': 'Female',
                        'msle': 'Male',
                        'Male-ish': 'Female',
                        'Guy (-ish) ^_^': 'Male',
                        'Female (trans)': 'Female',
                        'Trans woman': 'Female',
                        'Trans-female': 'Female'}, inplace=True)

df3.loc[(df3['Gender_0'] != 'Female') & (df3['Gender_0'] != 'Male'), 'Gender_0'] = "Unknown"
df3['Gender_0'].describe()

count     1259
unique       3
top       Male
freq       991
Name: Gender_0, dtype: object

In [10]:
df3['Gender_0']

0       Female
1         Male
2         Male
3         Male
4         Male
         ...  
1254      Male
1255      Male
1256      Male
1257    Female
1258      Male
Name: Gender_0, Length: 1259, dtype: object

In [11]:
df3.columns

Index(['Age', 'Gender', 'Country', 'state', 'self_employed', 'family_history',
       'treatment', 'work_interfere', 'no_employees', 'remote_work',
       'tech_company', 'benefits', 'care_options', 'wellness_program',
       'seek_help', 'anonymity', 'leave', 'mental_health_consequence',
       'phys_health_consequence', 'coworkers', 'supervisor',
       'mental_health_interview', 'phys_health_interview',
       'mental_vs_physical', 'obs_consequence', 'Gender_0'],
      dtype='object')

In [12]:
#Clean up age
df3['Age'].describe()

count    1.259000e+03
mean     7.942815e+07
std      2.818299e+09
min     -1.726000e+03
25%      2.700000e+01
50%      3.100000e+01
75%      3.600000e+01
max      1.000000e+11
Name: Age, dtype: float64

In [13]:
#df3.loc[(df3['Age']<18) | (df3['Age']>80)]=None

In [14]:
#creates 2 groups 
#df3.loc[(df3['Age']<18) | (df3['Age']>80), 'Age']=None
#df3['Age_Group'] = df3['Age']
#df3['Age_Group'] = df3['Age_Group'] >30 
#df3['Age_Group'] = df3['Age_Group'].map({False:"18-30", True:">30years"}) 
#df3['Age_Group'].value_counts()

In [15]:
##creates 3 groups didnt use as 31-50 too small 

#df3.loc[(df3['Age']<18) | (df3['Age']>80), 'Age']=None
#df3['Age_Group'] = df3['Age']
#df3.loc[df3['Age']<=30, 'Age_Group'] = "18-30"
#df3.loc[df3['Age']>50, 'Age_Group'] = "greater_than 50"
#df3.loc[(df3['Age']>30) & (df3['Age']<=50), 'Age_Group'] = "31-50"
#df3['Age_Group'] = df3['Age_Group'].map({False:"18-30", True:">30years"}) #creates 2 groups 
#df3['Age_Group'].value_counts()

In [16]:
df3.loc[(df3['Age']<18) | (df3['Age']>80), 'Age']=None
df3['Age_Group'] = df3['Age']
df3.loc[df3['Age']<=30, 'Age_Group'] = "18-30"
df3.loc[df3['Age']>30, 'Age_Group'] = "greater_than 30"
#df3.loc[(df3['Age']>30) & (df3['Age']<=50), 'Age_Group'] = "31-50"
#df3['Age_Group'] = df3['Age_Group'].map({False:"18-30", True:">30years"}) #creates 2 groups 
df3['Age_Group'].value_counts()

greater_than 30    672
18-30              579
Name: Age_Group, dtype: int64

In [17]:
df3['Age']

0       37.0
1       44.0
2       32.0
3       31.0
4       31.0
        ... 
1254    26.0
1255    32.0
1256    34.0
1257    46.0
1258    25.0
Name: Age, Length: 1259, dtype: float64

In [18]:
df3.columns

Index(['Age', 'Gender', 'Country', 'state', 'self_employed', 'family_history',
       'treatment', 'work_interfere', 'no_employees', 'remote_work',
       'tech_company', 'benefits', 'care_options', 'wellness_program',
       'seek_help', 'anonymity', 'leave', 'mental_health_consequence',
       'phys_health_consequence', 'coworkers', 'supervisor',
       'mental_health_interview', 'phys_health_interview',
       'mental_vs_physical', 'obs_consequence', 'Gender_0', 'Age_Group'],
      dtype='object')

In [19]:
#try running the profiler on afew var of interest
columns_of_interest = ['Age_Group', 'Age', 'Gender_0', 'Country', 'self_employed',
       'family_history', 'treatment', 'work_interfere', 'no_employees',
       'remote_work', 'tech_company', 'benefits', 'care_options',
       'wellness_program', 'seek_help', 'anonymity', 'leave',
       'mental_health_consequence', 'phys_health_consequence', 'coworkers',
       'supervisor',
       'mental_vs_physical', 'obs_consequence']
profile = ProfileReport(df3.loc[:,columns_of_interest], 
                        title="Pandas Profiling Report")
profile

Summarize dataset:   0%|          | 0/36 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [20]:
#Generated a Contingency/2-way table

pd.crosstab(df3['Gender_0'],df3['treatment'],margins=True)

treatment   No  Yes   All
Gender_0                 
Female      78  174   252
Male       541  450   991
Unknown      3   13    16
All        622  637  1259

In [21]:
#Create a Custom Function to generate the 2-way tab with cell frequency and percentages 

def addpercentage(row):
    cell_1 = row['No']/row['All']*100
    cell_2 = row['Yes']/row['All']*100
    row['No'] = "{} ({:.1f}%)".format(row['No'],cell_1)
    row['Yes'] = "{} ({:.1f}%)".format(row['Yes'],cell_2)
    return row

In [22]:
#Generate a 2-way tab with cell frequency and percentages [Gender_0]

table = pd.crosstab(df3['Gender_0'],df3['treatment'],margins=True)
table.apply(addpercentage, axis=1)

treatment           No          Yes   All
Gender_0                                 
Female      78 (31.0%)  174 (69.0%)   252
Male       541 (54.6%)  450 (45.4%)   991
Unknown      3 (18.8%)   13 (81.2%)    16
All        622 (49.4%)  637 (50.6%)  1259

In [23]:
#Generate a 2-way tab with cell frequency and percentages [self_employed]

table_1 = pd.crosstab(df3['self_employed'],df3['treatment'],margins=True)
table_1.apply(addpercentage, axis=1)

treatment               No          Yes   All
self_employed                                
No             545 (49.8%)  550 (50.2%)  1095
Yes             68 (46.6%)   78 (53.4%)   146
All            613 (49.4%)  628 (50.6%)  1241

In [24]:
#Generate a 2-way tab with cell frequency and percentages [family_history]

table_2 = pd.crosstab(df3['family_history'],df3['treatment'],margins=True)
table_2.apply(addpercentage, axis=1)

treatment                No          Yes   All
family_history                                
No              495 (64.5%)  272 (35.5%)   767
Yes             127 (25.8%)  365 (74.2%)   492
All             622 (49.4%)  637 (50.6%)  1259

In [25]:
#Generate a 2-way tab with cell frequency and percentages [no_employees]

table_3 = pd.crosstab(df3['no_employees'],df3['treatment'],margins=True)
table_3.apply(addpercentage, axis=1)

treatment                No          Yes   All
no_employees                                  
100-500          81 (46.0%)   95 (54.0%)   176
26-100          139 (48.1%)  150 (51.9%)   289
44317            71 (43.8%)   91 (56.2%)   162
45809           162 (55.9%)  128 (44.1%)   290
500-1000         33 (55.0%)   27 (45.0%)    60
More than 1000  136 (48.2%)  146 (51.8%)   282
All             622 (49.4%)  637 (50.6%)  1259

In [26]:
#Generate a 2-way tab with cell frequency and percentages [remote_work]

table_4 = pd.crosstab(df3['remote_work'],df3['treatment'],margins=True)
table_4.apply(addpercentage, axis=1)

treatment             No          Yes   All
remote_work                                
No           444 (50.3%)  439 (49.7%)   883
Yes          178 (47.3%)  198 (52.7%)   376
All          622 (49.4%)  637 (50.6%)  1259

In [27]:
#Generate a 2-way tab with cell frequency and percentages [care_options]

table_5 = pd.crosstab(df3['care_options'],df3['treatment'],margins=True)
table_5.apply(addpercentage, axis=1)

treatment              No          Yes   All
care_options                                
No            294 (58.7%)  207 (41.3%)   501
Not sure      191 (60.8%)  123 (39.2%)   314
Yes           137 (30.9%)  307 (69.1%)   444
All           622 (49.4%)  637 (50.6%)  1259

In [28]:
#Generate a 2-way tab with cell frequency and percentages [seek_help]

table_6 = pd.crosstab(df3['seek_help'],df3['treatment'],margins=True)
table_6.apply(addpercentage, axis=1)

treatment            No          Yes   All
seek_help                                 
Don't know  197 (54.3%)  166 (45.7%)   363
No          323 (50.0%)  323 (50.0%)   646
Yes         102 (40.8%)  148 (59.2%)   250
All         622 (49.4%)  637 (50.6%)  1259

In [29]:
#Generate a 2-way tab with cell frequency and percentages [anonymity]

table_7 = pd.crosstab(df3['anonymity'],df3['treatment'],margins=True)
table_7.apply(addpercentage, axis=1)

treatment            No          Yes   All
anonymity                                 
Don't know  448 (54.7%)  371 (45.3%)   819
No           27 (41.5%)   38 (58.5%)    65
Yes         147 (39.2%)  228 (60.8%)   375
All         622 (49.4%)  637 (50.6%)  1259

In [30]:
#Generate a 2-way tab with cell frequency and percentages [leave]

table_8 = pd.crosstab(df3['leave'],df3['treatment'],margins=True)
table_8.apply(addpercentage, axis=1)

treatment                    No          Yes   All
leave                                             
Don't know          309 (54.9%)  254 (45.1%)   563
Somewhat difficult   44 (34.9%)   82 (65.1%)   126
Somewhat easy       135 (50.8%)  131 (49.2%)   266
Very difficult       31 (31.6%)   67 (68.4%)    98
Very easy           103 (50.0%)  103 (50.0%)   206
All                 622 (49.4%)  637 (50.6%)  1259

In [31]:
#Chi-square Test: Applied when you have 2 categorical variables from a single population. 
#It is used to determine whethere there is a significant association between the 2 variables. 

import scipy.stats as stats


In [32]:
#Null Hypothesis: there is no association in Mental Health treatment between males and females 
#Alternate Hypothesis: there is an association in Mental Health treatment between males and females 
#Significant Value = 5% (i.e. 95% Confidence Level)
#Calcuate Critical value (Gender_0)
#degree of freedom (dof) = 2

In [33]:
# Display 2 by 2 dimensional table for Gender_0

table = pd.crosstab(df3['Gender_0'],df3['treatment'],margins=True)
table.apply(addpercentage, axis=1)

treatment           No          Yes   All
Gender_0                                 
Female      78 (31.0%)  174 (69.0%)   252
Male       541 (54.6%)  450 (45.4%)   991
Unknown      3 (18.8%)   13 (81.2%)    16
All        622 (49.4%)  637 (50.6%)  1259

In [34]:
# Display array for Gender_0

table.values

array([[  78,  174,  252],
       [ 541,  450,  991],
       [   3,   13,   16],
       [ 622,  637, 1259]], dtype=int64)

In [35]:
#Observed Values for Gender_0 

Observed_Values = table.values
print("Observed Values : \n" ,Observed_Values)

Observed Values : 
 [[  78  174  252]
 [ 541  450  991]
 [   3   13   16]
 [ 622  637 1259]]


In [36]:
#Apply chi2_contingency function within the 'stats' library

val = stats.chi2_contingency(table)

In [37]:
#Display val to display p square 

val

(51.00616141188284,
 2.9534753445387044e-09,
 6,
 array([[ 124.49880858,  127.50119142,  252.        ],
        [ 489.59650516,  501.40349484,  991.        ],
        [   7.90468626,    8.09531374,   16.        ],
        [ 622.        ,  637.        , 1259.        ]]))